# Generated by Django 2.2.10 on 2020-02-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='should',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
